extension_dir = "C:\Users\Tawreed Tech\scoop\apps\php\current\ext"
extension=curl
extension=fileinfo
extension=mbstring
extension=openssl
extension=pdo_mysql
extension=pdo_sqlite
extension=sqlite3
extension=zip

curl.cainfo = "D:/citysoftai/cacert.pem"
openssl.cafile = "D:/citysoftai/cacert.pem"
